//! Level data: tile properties, the entity table, and the file parser.
//!
//! Some items here are consumed by gameplay modules that are still being built
//! out, so the module tolerates currently-unused API rather than deleting things
//! the next layer needs.
#![allow(dead_code, unused_imports)]

//!
//! Everything here is pure data handling with no rendering or gameplay, which is
//! why it can be exhaustively tested against all 73 shipped level files without a
//! window or a GPU. That test is the strongest net against "world 5-2 crashes on
//! load" — the failure mode a 1-level port can't see.

pub mod entities;
pub mod parse;
pub mod tiles;

pub use entities::{EntityKind, Gel, GelFace};
pub use parse::{Gels, LEFT_PADDING, LEVEL_HEIGHT, Level, LevelMeta, Markers, ParseError};

// Every shipped level: `(mappack, name, raw text)`, generated by `build.rs`.
//
// Embedded at compile time rather than read from disk because the engine has no
// runtime asset loading, and the web build's prefetch only covers the
// textures/fonts/audio maps in `game.yaml`.
include!(concat!(env!("OUT_DIR"), "/levels.rs"));

/// Look up a level's raw text by mappack and name (e.g. `("smb", "1-1")`).
pub fn raw_level(pack: &str, name: &str) -> Option<&'static str> {
    LEVELS
        .iter()
        .find(|(p, n, _)| *p == pack && *n == name)
        .map(|(_, _, raw)| *raw)
}

/// Parse a level by mappack and name.
pub fn load(pack: &str, name: &str) -> Option<Result<Level, ParseError>> {
    raw_level(pack, name).map(Level::parse)
}

/// Every level name in a mappack, in sorted order.
pub fn level_names(pack: &str) -> Vec<&'static str> {
    LEVELS
        .iter()
        .filter(|(p, _, _)| *p == pack)
        .map(|(_, n, _)| *n)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The headline test: **every shipped level parses**.
    ///
    /// A 1-level port cannot discover that world 5-2 has a cell shape the loader
    /// chokes on. This walks all 73 files and asserts the invariants that must
    /// hold for the level to be playable at all.
    #[test]
    fn every_shipped_level_parses() {
        assert_eq!(LEVELS.len(), 73, "expected 64 smb + 9 portal");
        let mut failures = Vec::new();
        for (pack, name, raw) in LEVELS {
            match Level::parse(raw) {
                Ok(level) => {
                    if level.height != LEVEL_HEIGHT {
                        failures.push(format!("{pack}/{name}: height {}", level.height));
                    }
                    if level.data_width() == 0 {
                        failures.push(format!("{pack}/{name}: zero width"));
                    }
                }
                Err(e) => failures.push(format!("{pack}/{name}: {e}")),
            }
        }
        assert!(
            failures.is_empty(),
            "levels failed to parse:\n{failures:#?}"
        );
    }

    #[test]
    fn level_widths_match_the_originals() {
        // Spot-checks across the full range, including the two extremes: 8-1 is
        // the widest level in the game at 400, and the pipe stubs are 17.
        let cases = [
            ("smb", "1-1", 224usize),
            ("smb", "1-2", 24),
            ("smb", "1-2_1", 192),
            ("smb", "1-3", 176),
            ("smb", "1-4", 160),
            ("smb", "2-3", 240),
            ("smb", "8-1", 400),
            ("smb", "8-4", 97),
            ("smb", "M-1", 192),
            ("smb", "1-1_1", 17),
        ];
        for (pack, name, expected) in cases {
            let level = load(pack, name)
                .unwrap_or_else(|| panic!("{pack}/{name} missing"))
                .unwrap_or_else(|e| panic!("{pack}/{name}: {e}"));
            assert_eq!(level.data_width(), expected, "{pack}/{name} width");
        }
    }

    #[test]
    fn metadata_matches_the_originals() {
        // 1-4 is a castle (spriteset 3, music 4); 2-2_1 is underwater
        // (spriteset 4, music 5); 1-3 has the shorter 300 timer.
        let castle = load("smb", "1-4").unwrap().unwrap();
        assert_eq!(castle.meta.spriteset, 3);
        assert_eq!(castle.meta.music, 4);

        let water = load("smb", "2-2_1").unwrap().unwrap();
        assert_eq!(water.meta.spriteset, 4);
        assert_eq!(water.meta.music, 5);
        assert!(water.meta.underwater, "2-2_1 should be flagged underwater");

        let short = load("smb", "1-3").unwrap().unwrap();
        assert_eq!(short.meta.timelimit, 300);

        let stub = load("smb", "1-2").unwrap().unwrap();
        assert!(stub.meta.intermission, "1-2 is a 24-wide intermission stub");
    }

    #[test]
    fn one_one_has_the_landmarks_we_know_it_has() {
        let level = load("smb", "1-1").unwrap().unwrap();
        // Spawn, flagpole and the pipe-warp pair are all present, and were all
        // silently dropped by the previous loader.
        // 1-1 carries no `spawn` entity — like most levels it relies on the
        // original's default start tile.
        assert_eq!(level.markers.spawn, None);
        assert_eq!(
            level.markers.spawn_or_default(),
            (3, 13),
            "must fall back to the original's startx=3, starty=13"
        );
        assert!(level.markers.flag.is_some(), "1-1 must have a flagpole");
        assert!(
            !level.markers.pipes.is_empty(),
            "1-1 has a pipe into the coin room"
        );
        assert!(
            !level.markers.enemies.is_empty(),
            "1-1 has goombas and a koopa"
        );
        assert!(
            !level.markers.block_contents.is_empty(),
            "1-1 has mushroom and star blocks"
        );
    }

    #[test]
    fn every_level_resolves_a_start_position() {
        // `spawn` is optional — most levels omit it and take the default start
        // tile. What must always hold is that a start resolves and lands inside
        // the level's bounds.
        for (pack, name, raw) in LEVELS {
            let level = Level::parse(raw).expect("parses");
            let (sx, sy) = level.markers.spawn_or_default();
            assert!(
                sx < level.width && sy < level.height,
                "{pack}/{name}: start ({sx}, {sy}) is outside {}x{}",
                level.width,
                level.height
            );
        }
    }

    #[test]
    fn every_level_has_a_way_out() {
        // Flagpole, axe, a pipe, a vine, or (for intermission stubs) running off
        // the right edge. A level with none of these is a dead end.
        let mut dead_ends = Vec::new();
        for (pack, name, raw) in LEVELS {
            let l = Level::parse(raw).expect("parses");
            let m = &l.markers;
            let has_exit = m.flag.is_some()
                || m.axe.is_some()
                || !m.pipes.is_empty()
                || !m.vines.is_empty()
                || !m.warp_pipes.is_empty()
                || l.meta.intermission
                || l.meta.bonusstage;
            if !has_exit {
                dead_ends.push(format!("{pack}/{name}"));
            }
        }
        assert!(dead_ends.is_empty(), "levels with no exit:\n{dead_ends:#?}");
    }

    #[test]
    fn all_entity_ids_used_by_shipped_levels_resolve() {
        // If any level references an entity id we don't map, the level would load
        // with a hole in it. Sweep every cell of every level.
        let mut unresolved: std::collections::BTreeSet<u16> = Default::default();
        for (_, _, raw) in LEVELS {
            let cells = raw.split(';').next().unwrap_or("");
            for token in cells.split(',') {
                let mut parts = token.trim().split('-');
                let _tile = parts.next();
                if let Some(entity) = parts.next() {
                    if entity == "link" {
                        continue;
                    }
                    if let Ok(id) = entity.parse::<u16>()
                        && EntityKind::from_id(id).is_none()
                    {
                        unresolved.insert(id);
                    }
                }
            }
        }
        assert!(
            unresolved.is_empty(),
            "level data uses entity ids we don't map: {unresolved:?}"
        );
    }

    #[test]
    fn portal_mappack_uses_lab_elements_and_the_high_tile_range() {
        // Sanity that the portal pack really is the lab half: it should reference
        // tiles above the smb range and place lab entities.
        let mut saw_high_tile = false;
        let mut saw_lab = false;
        for name in level_names("portal") {
            let l = load("portal", name).unwrap().unwrap();
            if !l.markers.lab.is_empty() {
                saw_lab = true;
            }
            for y in 0..l.height {
                for x in 0..l.width {
                    if l.tile(x as i32, y as i32) > tiles::SMB_TILE_COUNT as u16 {
                        saw_high_tile = true;
                    }
                }
            }
        }
        assert!(saw_high_tile, "portal levels should use portaltiles ids");
        assert!(saw_lab, "portal levels should place lab elements");
    }

    #[test]
    fn maze_levels_have_matched_spans() {
        // The looping castles rely on start/end pairs; an unbalanced set would
        // make the corridor extend forever.
        for (pack, name, raw) in LEVELS {
            let l = Level::parse(raw).expect("parses");
            let m = &l.markers;
            assert_eq!(
                m.maze_starts.len(),
                m.maze_ends.len(),
                "{pack}/{name} has {} maze starts but {} ends",
                m.maze_starts.len(),
                m.maze_ends.len()
            );
        }
    }

    #[test]
    fn lookup_helpers_behave() {
        assert!(raw_level("smb", "1-1").is_some());
        assert!(raw_level("smb", "9-9").is_none());
        assert!(raw_level("nosuchpack", "1-1").is_none());
        assert!(load("smb", "nope").is_none());
        assert_eq!(level_names("smb").len(), 64);
        assert_eq!(level_names("portal").len(), 9);
    }
}
