//! Generates the tile property table by decoding marker pixels out of the
//! tilesheets, plus the level manifest.
//!
//! ## Why this is generated rather than written by hand
//!
//! Mari0 does not store tile properties in a table anywhere. Each 17×17 cell of
//! `smbtiles.png` / `portaltiles.png` carries its flags in the **17th column** —
//! the "extra" pixel that looks like padding is actually metadata. `quad.lua`
//! reads six alpha values from it:
//!
//! | row offset | property |
//! |---|---|
//! | +0 | collision |
//! | +1 | invisible |
//! | +2 | breakable |
//! | +3 | coinblock |
//! | +4 | coin |
//! | +5 | **not** portalable (inverted: alpha > 0.5 means portals are refused) |
//!
//! There are 220 tiles. Transcribing them by hand would be 220 chances to make a
//! silent mistake that only shows up as one wrong block in one level — and it
//! would go stale the moment a tilesheet is touched. Decoding the PNGs at build
//! time cannot drift.

use std::io::Write;
use std::path::{Path, PathBuf};

/// `(texture key, width in blocks, height in blocks)`.
type Layer = (String, f32, f32);
/// All layers that share the same level prefix within a mappack.
type LayerSet = Vec<Layer>;
/// `(level prefix, layers for that level)`.
type LevelGroup = (String, LayerSet);
/// `(mappack, level prefix, layers for that level)`. An empty level prefix means the
/// pack has no per-level backgrounds and the layers belong to the pack as a whole.
type PackSet = (String, String, LayerSet);

/// Cell stride in the tilesheets. 16px of art plus 1px of metadata.
const CELL: u32 = 17;

const FLAG_COLLISION: u8 = 1 << 0;
const FLAG_INVISIBLE: u8 = 1 << 1;
const FLAG_BREAKABLE: u8 = 1 << 2;
const FLAG_COINBLOCK: u8 = 1 << 3;
const FLAG_COIN: u8 = 1 << 4;
const FLAG_PORTALABLE: u8 = 1 << 5;

fn main() {
    let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("assets");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    let smb = assets.join("mari0/smbtiles.png");
    let portal = assets.join("mari0/portaltiles.png");
    println!("cargo:rerun-if-changed={}", smb.display());
    println!("cargo:rerun-if-changed={}", portal.display());

    // ── The stock sheets, then one block per mappack that adds its own ──
    //
    // A mappack's `tiles.png` does not *replace* the stock sheets — it is appended after
    // them (`game.lua:80-99`). So ids 1..=132 are always smbtiles and 133..=220 always
    // portaltiles, whatever pack you are playing, and a custom sheet only ever introduces
    // **new** ids from 221 up. Four of the DLC packs use them: smb2J reaches 352,
    // the untitled game 496, acid trip 718.
    //
    // Which means the shared range needs no per-pack anything, and only ids past 220 do.
    // `load_level` shifts just those into the pack's block, so `props()` and `is_solid()`
    // stay plain array lookups — 34 call sites, several in the physics hot path, that never
    // learn packs exist.
    //
    // Getting this wrong is instructive: reading a custom sheet as if it *replaced*
    // smbtiles makes `acid trip`'s sky solid and `the untitled game`'s sky opaque magenta,
    // because id 1 then points at the custom sheet's top-left cell instead of empty air.
    let mut props: Vec<u8> = Vec::new();
    // Index 0 is unused padding so the array can be indexed by a 1-based tile id directly.
    props.push(0);
    let smb_count = decode_sheet(&smb, &mut props);
    let portal_count = decode_sheet(&portal, &mut props);
    let shared = props.len();

    let levels_root = assets.join("levels");
    println!("cargo:rerun-if-changed={}", levels_root.display());
    let mut packs: Vec<String> = std::fs::read_dir(&levels_root)
        .unwrap_or_else(|e| panic!("read {}: {e}", levels_root.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    packs.sort();

    // (pack, custom_base, custom_cells, sheet_h, texture)
    let mut sheets: Vec<(String, u16, u16, u32, String)> = Vec::new();
    for pack in &packs {
        let own = levels_root.join(pack).join("tiles.png");
        if !own.exists() {
            sheets.push((pack.clone(), 0, 0, 0, "tiles".to_string()));
            continue;
        }
        println!("cargo:rerun-if-changed={}", own.display());
        let custom_base = props.len() as u16;
        let cells = decode_sheet(&own, &mut props);
        let sheet_h = image::open(&own)
            .unwrap_or_else(|e| panic!("open {}: {e}", own.display()))
            .height();
        sheets.push((
            pack.clone(),
            custom_base,
            cells as u16,
            sheet_h,
            format!("tiles_{pack}"),
        ));
    }
    assert_eq!(shared, 1 + smb_count + portal_count);

    let mut f = std::fs::File::create(out_dir.join("tile_props.rs")).expect("create tile_props.rs");
    writeln!(f, "// @generated by build.rs — do not edit.").unwrap();
    writeln!(
        f,
        "// Decoded from the 17th-column marker pixels of the tilesheets."
    )
    .unwrap();
    writeln!(f, "pub const SMB_TILE_COUNT: usize = {smb_count};").unwrap();
    writeln!(f, "pub const PORTAL_TILE_COUNT: usize = {portal_count};").unwrap();
    writeln!(
        f,
        "/// The extra tiles one mappack appends past id {}, and the sheet that draws them.",
        smb_count + portal_count
    )
    .unwrap();
    writeln!(f, "pub struct PackSheet {{").unwrap();
    writeln!(f, "    pub pack: &'static str,").unwrap();
    writeln!(
        f,
        "    /// Index in [`TILE_PROPS`] of this pack's first custom cell, or 0 if it has none."
    )
    .unwrap();
    writeln!(f, "    pub custom_base: u16,").unwrap();
    writeln!(
        f,
        "    /// How many cells its own sheet holds. 0 if it has none."
    )
    .unwrap();
    writeln!(f, "    pub custom_cells: u16,").unwrap();
    writeln!(f, "    /// Its sheet's pixel height, for the UV divisor.").unwrap();
    writeln!(f, "    pub sheet_h: f32,").unwrap();
    writeln!(f, "    /// `game.yaml` texture key for that sheet.").unwrap();
    writeln!(f, "    pub texture: &'static str,").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(
        f,
        "pub const PACK_SHEETS: [PackSheet; {}] = [",
        sheets.len()
    )
    .unwrap();
    for (pack, custom_base, custom_cells, sheet_h, texture) in &sheets {
        writeln!(
            f,
            "    PackSheet {{ pack: {pack:?}, custom_base: {custom_base}, custom_cells: {custom_cells}, sheet_h: {sheet_h}.0, texture: {texture:?} }},"
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f, "pub const TILE_PROPS: [u8; {}] = [", props.len()).unwrap();
    for chunk in props.chunks(22) {
        write!(f, "   ").unwrap();
        for v in chunk {
            write!(f, " 0x{v:02X},").unwrap();
        }
        writeln!(f).unwrap();
    }
    writeln!(f, "];").unwrap();

    generate_level_manifest(&assets, &out_dir);
    generate_background_manifest(&assets, &out_dir);
}

/// Emit `BACKGROUND_SETS`: the parallax backdrops each mappack supplies.
///
/// A level asks for one with `custombackground` or `portalbackground`, and the original
/// then looks for `<level>background1.png`, `2`, … in the pack; failing that
/// `background1.png`, …; failing that the stock `portalbackground.png`
/// (`main.lua:1653-1684`). So the *set* is chosen per level but the images belong to the
/// pack, and which exist can only be known by looking — hence a generated table.
///
/// Sizes are in blocks, as the original stores them (`img:getWidth()/16`), because the
/// draw loop tiles by block.
fn generate_background_manifest(assets: &Path, out_dir: &Path) {
    let levels_root = assets.join("levels");
    let mut packs: Vec<String> = std::fs::read_dir(&levels_root)
        .unwrap_or_else(|e| panic!("read {}: {e}", levels_root.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    packs.sort();

    // (pack, level-or-empty, [(texture key, w blocks, h blocks)])
    let mut sets: Vec<PackSet> = Vec::new();
    for pack in &packs {
        let dir = levels_root.join(pack);
        let mut found: Vec<(String, u32, PathBuf)> = Vec::new();
        for entry in std::fs::read_dir(&dir).into_iter().flatten().flatten() {
            let path = entry.path();
            let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
                continue;
            };
            let Some(rest) = name.strip_suffix(".png") else {
                continue;
            };
            let Some((prefix, index)) = rest.rsplit_once("background") else {
                continue;
            };
            let Ok(index) = index.parse::<u32>() else {
                continue;
            };
            found.push((prefix.to_string(), index, path));
        }
        if found.is_empty() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", dir.display());
        found.sort();
        // Group by level prefix, keeping each group in layer order. The original stops at
        // the first missing index, so a gap truncates the set rather than skipping a layer.
        let mut by_level: Vec<LevelGroup> = Vec::new();
        for (prefix, index, path) in found {
            let img = image::open(&path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
            let key = if prefix.is_empty() {
                format!("bg_{pack}_{index}")
            } else {
                format!("bg_{pack}_{prefix}_{index}")
            };
            let layer = (key, img.width() as f32 / 16.0, img.height() as f32 / 16.0);
            match by_level.last_mut() {
                Some((lvl, layers)) if *lvl == prefix => layers.push(layer),
                _ => by_level.push((prefix.clone(), vec![layer])),
            }
        }
        for (level, layers) in by_level {
            sets.push((pack.clone(), level, layers));
        }
    }

    let mut f =
        std::fs::File::create(out_dir.join("backgrounds.rs")).expect("create backgrounds.rs");
    writeln!(f, "// @generated by build.rs — do not edit.").unwrap();
    writeln!(f, "pub struct BackgroundLayer {{").unwrap();
    writeln!(f, "    pub texture: &'static str,").unwrap();
    writeln!(
        f,
        "    /// Size in blocks, which is what the draw loop tiles by."
    )
    .unwrap();
    writeln!(f, "    pub w: f32,").unwrap();
    writeln!(f, "    pub h: f32,").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f, "pub struct BackgroundSet {{").unwrap();
    writeln!(f, "    pub pack: &'static str,").unwrap();
    writeln!(
        f,
        "    /// Level this set is for, or \"\" for the pack-wide default."
    )
    .unwrap();
    writeln!(f, "    pub level: &'static str,").unwrap();
    writeln!(
        f,
        "    /// Nearest layer first, as the level files number them."
    )
    .unwrap();
    writeln!(f, "    pub layers: &'static [BackgroundLayer],").unwrap();
    writeln!(f, "}}").unwrap();
    for (i, (_, _, layers)) in sets.iter().enumerate() {
        writeln!(f, "const BG_{i}: [BackgroundLayer; {}] = [", layers.len()).unwrap();
        for (key, w, h) in layers {
            writeln!(
                f,
                "    BackgroundLayer {{ texture: {key:?}, w: {w:?}, h: {h:?} }},"
            )
            .unwrap();
        }
        writeln!(f, "];").unwrap();
    }
    writeln!(
        f,
        "pub const BACKGROUND_SETS: [BackgroundSet; {}] = [",
        sets.len()
    )
    .unwrap();
    for (i, (pack, level, _)) in sets.iter().enumerate() {
        writeln!(
            f,
            "    BackgroundSet {{ pack: {pack:?}, level: {level:?}, layers: &BG_{i} }},"
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
}

/// Append one sheet's tiles to `props`, returning how many were decoded.
fn decode_sheet(path: &Path, props: &mut Vec<u8>) -> usize {
    let img = image::open(path)
        .unwrap_or_else(|e| panic!("open {}: {e}", path.display()))
        .to_rgba8();
    let (w, h) = img.dimensions();
    let cols = w / CELL;
    let rows = h / CELL;

    // Row-major, 1-based — matching `main.lua`'s nested loops, which is what
    // determines the id of every tile.
    for y in 1..=rows {
        for x in 1..=cols {
            let marker_x = x * CELL - 1;
            let mut flags = 0u8;
            // Default is "portalable"; the marker pixel *clears* it.
            let mut portalable = true;
            for (offset, bit) in [
                (0, FLAG_COLLISION),
                (1, FLAG_INVISIBLE),
                (2, FLAG_BREAKABLE),
                (3, FLAG_COINBLOCK),
                (4, FLAG_COIN),
            ] {
                if marker_set(&img, marker_x, (y - 1) * CELL + offset) {
                    flags |= bit;
                }
            }
            if marker_set(&img, marker_x, (y - 1) * CELL + 5) {
                portalable = false;
            }
            if portalable {
                flags |= FLAG_PORTALABLE;
            }
            props.push(flags);
        }
    }
    (cols * rows) as usize
}

/// A marker is set when its alpha exceeds half — the same `alpha > 0.5` test
/// Löve applies to its normalized float pixels.
fn marker_set(img: &image::RgbaImage, x: u32, y: u32) -> bool {
    if x >= img.width() || y >= img.height() {
        return false;
    }
    img.get_pixel(x, y)[3] > 127
}

/// Emit `LEVELS`: every level file's name and contents, embedded.
///
/// Levels must be compile-time embedded rather than read at runtime, because the
/// engine offers no runtime asset loading and the web build's prefetch only
/// covers the textures/fonts/audio maps in `game.yaml`. 75 files of terse CSV is
/// well under a megabyte, so embedding costs little.
fn generate_level_manifest(assets: &Path, out_dir: &Path) {
    let mut entries: Vec<(String, String, PathBuf)> = Vec::new();
    // Enumerated rather than listed, so adding a mappack is a matter of dropping its
    // directory in. It has to stay sorted for the generated table to be stable across
    // machines, and `menu::PACKS` decides the *menu* order separately — a pack that is
    // embedded but not listed there is simply unreachable rather than broken.
    let levels_root = assets.join("levels");
    println!("cargo:rerun-if-changed={}", levels_root.display());
    let mut packs: Vec<String> = std::fs::read_dir(&levels_root)
        .unwrap_or_else(|e| panic!("read {}: {e}", levels_root.display()))
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    packs.sort();
    for pack in &packs {
        let dir = levels_root.join(pack);
        println!("cargo:rerun-if-changed={}", dir.display());
        let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().is_some_and(|e| e == "txt"))
            // A mappack directory also holds its own metadata, and neither file is a
            // level: `settings.txt` names the pack and `version.txt` is one line of
            // integer. Feeding either to the parser fails with "not a multiple of 15",
            // which is how they were noticed.
            .filter(|p| {
                p.file_stem()
                    .is_some_and(|s| s != "settings" && s != "version")
            })
            .collect();
        // Sorted so the generated table is stable across machines.
        files.sort();
        for path in files {
            let stem = path.file_stem().unwrap().to_string_lossy().to_string();
            entries.push((pack.clone(), stem, path));
        }
    }

    let mut f = std::fs::File::create(out_dir.join("levels.rs")).expect("create levels.rs");
    writeln!(f, "// @generated by build.rs — do not edit.").unwrap();
    writeln!(
        f,
        "/// (mappack, level name, raw level text) for every shipped level."
    )
    .unwrap();
    writeln!(
        f,
        "pub const LEVELS: [(&str, &str, &str); {}] = [",
        entries.len()
    )
    .unwrap();
    for (pack, name, path) in &entries {
        writeln!(
            f,
            "    (\"{pack}\", \"{name}\", include_str!(r\"{}\")),",
            path.display()
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
}
