//! Generates the tile property table by decoding marker pixels out of the
//! tilesheets, plus the level manifest.
//!
//! ## Why this is generated rather than written by hand
//!
//! Mari0 does not store tile properties in a table anywhere. Each 17×17 cell of
//! `smbtiles.png` / `portaltiles.png` carries its flags in the **17th column** —
//! the "extra" pixel that looks like padding is actually metadata. `quad.lua`
//! reads six alpha values from it:
//!
//! | row offset | property |
//! |---|---|
//! | +0 | collision |
//! | +1 | invisible |
//! | +2 | breakable |
//! | +3 | coinblock |
//! | +4 | coin |
//! | +5 | **not** portalable (inverted: alpha > 0.5 means portals are refused) |
//!
//! There are 220 tiles. Transcribing them by hand would be 220 chances to make a
//! silent mistake that only shows up as one wrong block in one level — and it
//! would go stale the moment a tilesheet is touched. Decoding the PNGs at build
//! time cannot drift.

use std::io::Write;
use std::path::{Path, PathBuf};

/// Cell stride in the tilesheets. 16px of art plus 1px of metadata.
const CELL: u32 = 17;

const FLAG_COLLISION: u8 = 1 << 0;
const FLAG_INVISIBLE: u8 = 1 << 1;
const FLAG_BREAKABLE: u8 = 1 << 2;
const FLAG_COINBLOCK: u8 = 1 << 3;
const FLAG_COIN: u8 = 1 << 4;
const FLAG_PORTALABLE: u8 = 1 << 5;

fn main() {
    let assets = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("assets");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    let smb = assets.join("mari0/smbtiles.png");
    let portal = assets.join("mari0/portaltiles.png");
    println!("cargo:rerun-if-changed={}", smb.display());
    println!("cargo:rerun-if-changed={}", portal.display());

    let mut props: Vec<u8> = Vec::new();
    // Global tile ids are 1-based and concatenate the two sheets in this order:
    // smb occupies 1..=132, portal 133..=220. Index 0 is unused padding so the
    // generated array can be indexed directly by the level file's tile id.
    props.push(0);
    let smb_count = decode_sheet(&smb, &mut props);
    let portal_count = decode_sheet(&portal, &mut props);

    let mut f = std::fs::File::create(out_dir.join("tile_props.rs")).expect("create tile_props.rs");
    writeln!(f, "// @generated by build.rs — do not edit.").unwrap();
    writeln!(
        f,
        "// Decoded from the 17th-column marker pixels of the tilesheets."
    )
    .unwrap();
    writeln!(f, "pub const SMB_TILE_COUNT: usize = {smb_count};").unwrap();
    writeln!(f, "pub const PORTAL_TILE_COUNT: usize = {portal_count};").unwrap();
    writeln!(f, "pub const TILE_PROPS: [u8; {}] = [", props.len()).unwrap();
    for chunk in props.chunks(22) {
        write!(f, "   ").unwrap();
        for v in chunk {
            write!(f, " 0x{v:02X},").unwrap();
        }
        writeln!(f).unwrap();
    }
    writeln!(f, "];").unwrap();

    generate_level_manifest(&assets, &out_dir);
}

/// Append one sheet's tiles to `props`, returning how many were decoded.
fn decode_sheet(path: &Path, props: &mut Vec<u8>) -> usize {
    let img = image::open(path)
        .unwrap_or_else(|e| panic!("open {}: {e}", path.display()))
        .to_rgba8();
    let (w, h) = img.dimensions();
    let cols = w / CELL;
    let rows = h / CELL;

    // Row-major, 1-based — matching `main.lua`'s nested loops, which is what
    // determines the id of every tile.
    for y in 1..=rows {
        for x in 1..=cols {
            let marker_x = x * CELL - 1;
            let mut flags = 0u8;
            // Default is "portalable"; the marker pixel *clears* it.
            let mut portalable = true;
            for (offset, bit) in [
                (0, FLAG_COLLISION),
                (1, FLAG_INVISIBLE),
                (2, FLAG_BREAKABLE),
                (3, FLAG_COINBLOCK),
                (4, FLAG_COIN),
            ] {
                if marker_set(&img, marker_x, (y - 1) * CELL + offset) {
                    flags |= bit;
                }
            }
            if marker_set(&img, marker_x, (y - 1) * CELL + 5) {
                portalable = false;
            }
            if portalable {
                flags |= FLAG_PORTALABLE;
            }
            props.push(flags);
        }
    }
    (cols * rows) as usize
}

/// A marker is set when its alpha exceeds half — the same `alpha > 0.5` test
/// Löve applies to its normalized float pixels.
fn marker_set(img: &image::RgbaImage, x: u32, y: u32) -> bool {
    if x >= img.width() || y >= img.height() {
        return false;
    }
    img.get_pixel(x, y)[3] > 127
}

/// Emit `LEVELS`: every level file's name and contents, embedded.
///
/// Levels must be compile-time embedded rather than read at runtime, because the
/// engine offers no runtime asset loading and the web build's prefetch only
/// covers the textures/fonts/audio maps in `game.yaml`. 75 files of terse CSV is
/// well under a megabyte, so embedding costs little.
fn generate_level_manifest(assets: &Path, out_dir: &Path) {
    let mut entries: Vec<(String, String, PathBuf)> = Vec::new();
    for pack in ["smb", "portal"] {
        let dir = assets.join("levels").join(pack);
        println!("cargo:rerun-if-changed={}", dir.display());
        let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().is_some_and(|e| e == "txt"))
            .filter(|p| p.file_stem().is_some_and(|s| s != "settings"))
            .collect();
        // Sorted so the generated table is stable across machines.
        files.sort();
        for path in files {
            let stem = path.file_stem().unwrap().to_string_lossy().to_string();
            entries.push((pack.to_string(), stem, path));
        }
    }

    let mut f = std::fs::File::create(out_dir.join("levels.rs")).expect("create levels.rs");
    writeln!(f, "// @generated by build.rs — do not edit.").unwrap();
    writeln!(
        f,
        "/// (mappack, level name, raw level text) for every shipped level."
    )
    .unwrap();
    writeln!(
        f,
        "pub const LEVELS: [(&str, &str, &str); {}] = [",
        entries.len()
    )
    .unwrap();
    for (pack, name, path) in &entries {
        writeln!(
            f,
            "    (\"{pack}\", \"{name}\", include_str!(r\"{}\")),",
            path.display()
        )
        .unwrap();
    }
    writeln!(f, "];").unwrap();
}
